# Generated by Django 4.0.6 on 2022-07-07 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussion',
            old_name='likes_discussion',
            new_name='likes',
        ),
    ]
