# Generated by Django 4.0.6 on 2022-08-11 11:17

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_rename_date_cerated_message_date_created'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='message',
            managers=[
                ('unreaded_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
