# Generated by Django 4.0.6 on 2022-08-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_comment_profile_user_alter_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='telegram_id',
            field=models.IntegerField(default=0),
        ),
    ]
