# Generated by Django 4.0.6 on 2022-08-07 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_post_content_alter_post_title_notificationlike_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationcomment',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='notificationcomment',
            name='readable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationlike',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='notificationlike',
            name='readable',
            field=models.BooleanField(default=False),
        ),
    ]
