# Generated by Django 4.0.6 on 2022-08-07 15:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_notificationcomment_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationcomment',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='notificationlike',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
