# Generated by Django 4.0.6 on 2022-08-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_notificationcommentcreated'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='qr_image',
            field=models.ImageField(default='blank-profile-img.png', upload_to='qr_images'),
        ),
    ]
