# Generated by Django 4.0.6 on 2022-08-20 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_profile_qr_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(default='profile_images/blank-profile-img.png', upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='qr_image',
            field=models.ImageField(default='qr_images/blank-profile-img.png', upload_to='qr_images'),
        ),
    ]
