# Generated by Django 4.0.5 on 2022-07-22 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_likepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='profile_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.profile'),
            preserve_default=False,
        ),
    ]
