# Generated by Django 4.0.5 on 2022-07-04 13:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_likes_post_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, help_text='5000 symbols is max', max_length=2000, null=True),
        ),
    ]
